// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Join(arg1) {
  return window['go']['main']['App']['Join'](arg1);
}

export function Leave() {
  return window['go']['main']['App']['Leave']();
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function LocalBuild() {
  return window['go']['main']['App']['LocalBuild']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
