// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSettings():Promise<main.Settings>;

export function Join(arg1:string):Promise<void>;

export function Leave():Promise<void>;

export function ListServers():Promise<Array<main.ServerView>>;

export function LocalBuild():Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function Status():Promise<main.StatusView>;
