// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Ballot() {
  return window['go']['main']['App']['Ballot']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Join(arg1) {
  return window['go']['main']['App']['Join'](arg1);
}

export function Leave() {
  return window['go']['main']['App']['Leave']();
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function LocalBuild() {
  return window['go']['main']['App']['LocalBuild']();
}

export function OverlayKeyConflicts(arg1) {
  return window['go']['main']['App']['OverlayKeyConflicts'](arg1);
}

export function OverlaySupported() {
  return window['go']['main']['App']['OverlaySupported']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetFavorite'](arg1, arg2);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function Vote(arg1, arg2) {
  return window['go']['main']['App']['Vote'](arg1, arg2);
}
