// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Ballot():Promise<main.BallotView>;

export function CheckUpdate():Promise<main.UpdateInfo>;

export function Diagnostics():Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function Join(arg1:string):Promise<void>;

export function Leave():Promise<void>;

export function ListServers():Promise<Array<main.ServerView>>;

export function LocalBuild():Promise<string>;

export function OverlayKeyConflicts(arg1:Array<string>):Promise<Array<string>>;

export function OverlaySupported():Promise<boolean>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SetFavorite(arg1:string,arg2:boolean):Promise<void>;

export function Status():Promise<main.StatusView>;

export function Version():Promise<string>;

export function Vote(arg1:number,arg2:number):Promise<void>;
